// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCss360uL0L6kPG_BYs-m1mULdmx8vGtbY',
    appId: '1:443604130247:web:d9b228944a7579e91e21e2',
    messagingSenderId: '443604130247',
    projectId: 'e-commercea-app-using-bloc',
    authDomain: 'e-commercea-app-using-bloc.firebaseapp.com',
    storageBucket: 'e-commercea-app-using-bloc.firebasestorage.app',
    measurementId: 'G-LRSW22C5ZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGFM1D9m7LzBjJJFWyjd_pvM3xQeOyNh8',
    appId: '1:443604130247:android:8c5f0744a52651071e21e2',
    messagingSenderId: '443604130247',
    projectId: 'e-commercea-app-using-bloc',
    storageBucket: 'e-commercea-app-using-bloc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChciFRm45depmyiScYi6D15waStdHNA8M',
    appId: '1:443604130247:ios:33f925e8641208a51e21e2',
    messagingSenderId: '443604130247',
    projectId: 'e-commercea-app-using-bloc',
    storageBucket: 'e-commercea-app-using-bloc.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceAppWithBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChciFRm45depmyiScYi6D15waStdHNA8M',
    appId: '1:443604130247:ios:33f925e8641208a51e21e2',
    messagingSenderId: '443604130247',
    projectId: 'e-commercea-app-using-bloc',
    storageBucket: 'e-commercea-app-using-bloc.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceAppWithBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCss360uL0L6kPG_BYs-m1mULdmx8vGtbY',
    appId: '1:443604130247:web:4cdfec214cad25951e21e2',
    messagingSenderId: '443604130247',
    projectId: 'e-commercea-app-using-bloc',
    authDomain: 'e-commercea-app-using-bloc.firebaseapp.com',
    storageBucket: 'e-commercea-app-using-bloc.firebasestorage.app',
    measurementId: 'G-Q945Y7K2CX',
  );
}
